# fly.toml app configuration file generated for the-void-chronicles on 2025-08-10T11:41:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-void-chronicles'
primary_region = 'lhr'

[build]

[env]
  HTTP_PORT = "8080"
  SSH_HOST = "0.0.0.0"
  SSH_PORT = "2222"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# SSH Service on port 2222 internally, 10022 externally
[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [[services.ports]]
    port = 22

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
